import Head from "next/head";
import BannerSlider from "../components/BannerSlider/BannerSlider";
import CardList from "../components/CardList/CardList";

import { getVideosData } from "../lib/videos";

import styles from "../styles/Home.module.css";

export const getServerSideProps = async () => {
  const videosData = await getVideosData("eldenRing", 10);

  return { props: { videosData } };
};

export default function Home({ videosData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BannerSlider />
        <CardList
          listTitle="Test large cards"
          cards={videosData}
          numberPerRow={6}
          cardSize="large"
          autoPlayDelay={7000}
        />
        <CardList
          listTitle="Test small cards"
          cards={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
          numberPerRow={6}
          cardSize="small"
          autoPlayDelay={10000}
        />
        <CardList
          listTitle="Test medium cards"
          cards={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
          numberPerRow={10}
          cardSize="medium"
          autoPlayDelay={15000}
        />
      </main>
    </div>
  );
}
