import Head from "next/head";
import BannerSlider from "../components/BannerSlider/BannerSlider";
import Card from "../components/CardList/Card/Card";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BannerSlider />
        <Card size="small" />
        <Card size="medium" />
        <Card size="large" />
      </main>
    </div>
  );
}
